Streetcode/DbUpdate/Program.cs

dev
Bug Fix. Move 'Program' into a named namespace. 
Closes #17 
ToDo

Add namespace to DbUpdate.Program, change order of usings

---

Streetcode/Streetcode.XUnitTest/MediatRTests/Team/GetByIdTeamTests.cs
Streetcode/Streetcode.XUnitTest/Streetcode.XUnitTest.csproj

dev
Unit testingTeam/GetById Handler
Closes issue #30 
ToDo

Unit tests for Team/GetById Handler

---

Streetcode/Streetcode.XUnitTest/MediatRTests/Partners/GetPartnerByIdHandlerTests.cs

Created tests for Partners/getPartnersById

---

Streetcode/Streetcode.XUnitTest/MediatRTests/Partners/CreatePartnerHandlerTests (2).cs
Streetcode/Streetcode.XUnitTest/MediatRTests/Partners/CreatePartnerHandlerTests.cs

write tests for partners/create handler

---

Streetcode/Streetcode.DAL/Repositories/Interfaces/Base/IRepositoryBase.cs
Streetcode/Streetcode.DAL/Repositories/Realizations/Base/RepositoryBase.cs

added params to executeSqlRaw

---

Streetcode/Streetcode.BLL/MediatR/Toponyms/GetByStreetcodeId/GetToponymsByStreetcodeIdHandler.cs

Removed DistinctBy due to using GroupBy and First.

---

Streetcode/Streetcode.XUnitTest/MediatRTests/Streetcode/RelatedFigure/GetByStreetcodeId/GetRelatedFiguresByStreetcodeIdHandlerTests.cs
Streetcode/Streetcode.XUnitTest/MediatRTests/StreetcodeTests/RelatedFigureTests/GetByStreetcodeId/GetRelatedFiguresByStreetcodeIdHandlerTests.cs

Test/ssad 0008/unit test streetcode/related figure/get by streetcode

---

Streetcode/Streetcode.XUnitTest/MediatRTests/Streetcode/Term/GetTermByIdHandlerTests.cs

Get term by id unit test done

---

Streetcode/Streetcode.WebApi/Utils/WebParsingUtils.cs

ssl tls vulnerability fixed

---

Streetcode/Streetcode.BLL/DTO/Sources/CategoryContentUpdateDTO.cs
Streetcode/Streetcode.BLL/Mapping/Sources/StreetcodeCategoryContentProfile.cs
Streetcode/Streetcode.BLL/MediatR/Sources/SourceLinkCategory/UpdateContent/CategoryContentUpdateCommand.cs
Streetcode/Streetcode.BLL/MediatR/Sources/SourceLinkCategory/UpdateContent/CategoryContentUpdateHandler.cs
Streetcode/Streetcode.WebApi/Controllers/Source/SourcesController.cs
Streetcode/Streetcode.XUnitTest/MediatRTests/Sources/CategoryContentUpdateHandlerTests.cs

updateContent dto, mediatr, controller, tests

---

Streetcode/Streetcode.BLL/Mapping/Sources/StreetcodeCategoryContentProfile.cs
Streetcode/Streetcode.BLL/MediatR/Sources/SourceLinkCategory/DeleteContentCategory/DeleteContentCategoryHandler.cs
Streetcode/Streetcode.BLL/MediatR/Sources/SourceLinkCategory/DeleteContentCategory/DeleteContentCategoryQuery.cs
Streetcode/Streetcode.WebApi/Controllers/Source/SourcesController.cs
Streetcode/Streetcode.XUnitTest/MediatRTests/Sources/DeleteContentCategoryHandlerTests.cs

delete of streetcode content works correctly

---

Streetcode/Streetcode.BLL/DTO/Sources/Create/CreateSourceCategoryDTO.cs
Streetcode/Streetcode.BLL/Mapping/Sources/SourceLinkCategoryProfile.cs
Streetcode/Streetcode.BLL/MediatR/Sources/SourceLinkCategory/Create/CreateSourceLinkCategoryCommand.cs
Streetcode/Streetcode.BLL/MediatR/Sources/SourceLinkCategory/Create/CreateSourceLinkCategoryHandler.cs
Streetcode/Streetcode.WebApi/Controllers/Source/SourcesController.cs
Streetcode/Streetcode.XUnitTest/MediatRTests/Sources/CreateSourceLinkCategoryHandlerTests.cs

create category handler, controller, mapping, dto

---

Streetcode/Streetcode.BLL/MediatR/Instagram/GetAll/GetAllPostsHandler.cs
Streetcode/Streetcode.XUnitTest/MediatRTests/Instagram/GetAllPostsHandlerTests.cs

write tests for instagram GetAll + write posts > 0 check to handler

---

Streetcode/Streetcode.BLL/MediatR/AdditionalContent/Subtitle/GetAll/GetAllSubtitlesHandler.cs
Streetcode/Streetcode.XUnitTest/MediatRTests/AdditionalContent/Subtitle/GetAllSubtitlesHandlerTests.cs

refactor and write test for SubtitleGetAll
#101

103 unit testing and refactor for SubtitleGetAll

---

Streetcode/Streetcode.BLL/DTO/Streetcode/TextContent/Fact/FactDTO.cs
Streetcode/Streetcode.BLL/DTO/Streetcode/TextContent/Fact/FactUpdateCreateDto.cs
Streetcode/Streetcode.BLL/DTO/Streetcode/TextContent/Fact/FactUpdatePositionDTO.cs
Streetcode/Streetcode.BLL/MediatR/Streetcode/Fact/Reorder/ReorderFactsCommand.cs
Streetcode/Streetcode.BLL/MediatR/Streetcode/Fact/Reorder/ReorderFactsHandler.cs
Streetcode/Streetcode.DAL/Entities/Streetcode/TextContent/Fact.cs
Streetcode/Streetcode.WebApi/Controllers/Streetcode/TextContent/FactController.cs
Streetcode/Streetcode.XUnitTest/MediatRTests/Streetcode/Facts/ReorderFactsHandlerTests.cs
Streetcode/Streetcode.XUnitTest/Streetcode.XUnitTest.csproj

feat/105: implemented the ability to change the order of facts

---

Streetcode/Streetcode.DAL/Entities/Streetcode/TextContent/Fact.cs
Streetcode/Streetcode.DAL/Persistence/Migrations/20240617093850_UpdateFactModel.Designer.cs
Streetcode/Streetcode.DAL/Persistence/Migrations/20240617093850_UpdateFactModel.cs

1. In StreetcodeDbContext class paste this code with your full connection string
protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
{
optionsBuilder.UseSqlServer(
@"/*paste connection string*/");
}
2. Open Package Manager Console (Tools->NuGet Package Manager->Package Manager Console)
3. Write: update-database 
4. Remove OnConfiguring method from StreetcodeDbContext

Migration/add Position to Fact

---

Streetcode/Streetcode.BLL/DTO/Toponyms/StreetcodeRecordDTO.cs
Streetcode/Streetcode.BLL/MediatR/Toponyms/StreetCodeRecord/Create/CreateStreetcodeRecordCommand.cs
Streetcode/Streetcode.BLL/MediatR/Toponyms/StreetCodeRecord/Create/CreateStreetcodeRecordHandler.cs
Streetcode/Streetcode.BLL/Resources/ErrorMessages.Designer.cs
Streetcode/Streetcode.BLL/Resources/ErrorMessages.resx
Streetcode/Streetcode.WebApi/Controllers/Toponyms/StreetCodeRecordController.cs
Streetcode/Streetcode.XUnitTest/MediatRTests/Toponyms/StreetCodeRecord/CreateStreetcodeRecordHandlerTests.cs

Admin/History Map Add Record

---

Streetcode/Streetcode.BLL/Mapping/Toponyms/StreetcodeToponymProfile.cs
Streetcode/Streetcode.BLL/MediatR/Toponyms/StreetCodeRecord/Delete/DeleteStreetcodeRecordHandler.cs
Streetcode/Streetcode.BLL/MediatR/Toponyms/StreetCodeRecord/Delete/DeleteStreetcodeRecordQuery.cs
Streetcode/Streetcode.WebApi/Controllers/Toponyms/StreetCodeRecordController.cs
Streetcode/Streetcode.XUnitTest/MediatRTests/Toponyms/StreetCodeRecord/DeleteStreetcodeRecordHandlerTests.cs

Admin/HistoryMap/delete streetcodeToponym record

---

Streetcode/Streetcode.BLL/MediatR/Partners/Create/CreatePartnerHandler.cs
Streetcode/Streetcode.XUnitTest/MediatRTests/Partners/CreatePartnerHandlerTests.cs

add newpartner is null check to handler

---

Streetcode/Streetcode.XUnitTest/MediatRTests/Partners/DeletePartnerHandlerTests.cs

write tests for delete partner handler

---

Streetcode/Streetcode.BLL/MediatR/Media/Audio/GetByStreetcodeId/GetAudioByStreetcodeIdQueryHandler.cs

dev
closes #194 
removed duplicate assignment
ToDo

remove useless assignment

---

Streetcode/Streetcode.BLL/MediatR/AdditionalContent/Tag/GetByStreetcodeId/GetTagByStreetcodeIdHandler.cs
Streetcode/Streetcode.BLL/MediatR/Media/Art/GetByStreetcodeId/GetArtsByStreetcodeIdHandler.cs
Streetcode/Streetcode.BLL/MediatR/Media/StreetcodeArt/GetByStreetcodeId/GetStreetcodeArtByStreetcodeIdHandler.cs
Streetcode/Streetcode.BLL/MediatR/Toponyms/GetAll/GetAllToponymsHandler.cs

dev
* [Issue 190](https://github.com/project-studying-dotnet/Streetcode-Server-June/issues/190)
ToDo
Remove commented code 
ToDo
ToDo

chore/190: remove commented code

---

Streetcode/Streetcode.BLL/MediatR/Streetcode/Text/GetByStreetcodeId/GetTextByStreetcodeIdHandler.cs
Streetcode/Streetcode.BLL/Services/Payment/PaymentService.cs

dev
closes #193;
closes #196;
closes #195;

Fixed code-smells.

---

Streetcode/Streetcode.BLL/Interfaces/Users/ITokenService.cs
Streetcode/Streetcode.BLL/Services/Tokens/TokenService.cs
Streetcode/Streetcode.WebApi/Extensions/ServiceCollectionExtensions.cs

add DI for TokenService and add for Swagger filed to check accessToken

add DI for TokenService

---

Streetcode/Streetcode.BLL/MediatR/Account/Logout/LogoutUserCommand.cs
Streetcode/Streetcode.BLL/MediatR/Account/Logout/LogoutUserHandler.cs
Streetcode/Streetcode.WebApi/Controllers/Account/AccountController.cs

Added Logout endpoint (no handler implementation).

---

Streetcode/Streetcode.BLL/MediatR/Account/Register/RegisterUserRequestDTOValidator.cs

bug with valid rules difference fixed

---

Streetcode/Streetcode.WebApi/Controllers/Partners/PartnersController.cs
Streetcode/Streetcode.WebApi/Extensions/ServiceCollectionExtensions.cs
Streetcode/Streetcode.WebApi/Program.cs

Replace AddSwagger after adding authorization.
Changed swagger config.
dev
closes #258;

Fixed Swagger Authorization

---

Streetcode/Streetcode.WebApi/Program.cs

set cron weekly every monday at 3 am
#272

set cron weekly every monday at 3 am

---

Streetcode/Streetcode.BLL/MediatR/Account/Delete/DeleteUserCommand.cs
Streetcode/Streetcode.BLL/MediatR/Account/RefreshToken/RefreshTokenHandler.cs
Streetcode/Streetcode.BLL/MediatR/Account/Register/RegisterUserHandler.cs

Fixed bugs in refreshToke and delete UserHandler

---

Streetcode/Streetcode.BLL/Mapping/Tokens/TokenProfile.cs
Streetcode/Streetcode.BLL/Services/Tokens/TokenService.cs
Streetcode/Streetcode.XUnitTest/Services/TokenService/TokenServiceTests.cs

Refactor tokenservice

---

Streetcode/Streetcode.XUnitTest/Streetcode.XUnitTest.csproj

fix references in project Unit tests

fix references in Unit tests

---

Streetcode/Streetcode.BLL/MediatR/Comments/GetAll/GetAllCommentsHandler.cs
Streetcode/Streetcode.BLL/MediatR/Comments/GetAll/GetAllCommentsQuery.cs
Streetcode/Streetcode.WebApi/Controllers/Comment/CommentController.cs
Streetcode/Streetcode.XUnitTest/MediatRTests/Comments/GetAllCommentsHandlerTests.cs

Added Endpoint and Handler for GetAllComments.

---

Streetcode/Streetcode.BLL/DTO/Users/LoginWithGoogleDTO.cs
Streetcode/Streetcode.BLL/DTO/Users/UserDTO.cs
Streetcode/Streetcode.BLL/MediatR/Account/LoginWithGoogle/LoginWithGoogleCommand.cs
Streetcode/Streetcode.BLL/MediatR/Account/LoginWithGoogle/LoginWithGoogleHandler.cs
Streetcode/Streetcode.BLL/MediatR/Account/LoginWithGoogle/LoginWithGoogleRequestDTOValidator.cs
Streetcode/Streetcode.BLL/Services/Tokens/TokensConfiguration.cs
Streetcode/Streetcode.BLL/Streetcode.BLL.csproj
Streetcode/Streetcode.DAL/Streetcode.DAL.csproj
Streetcode/Streetcode.WebApi/Controllers/Account/AccountController.cs
Streetcode/Streetcode.WebApi/Streetcode.WebApi.csproj
Streetcode/Streetcode.WebApi/libman.json
Streetcode/Streetcode.XIntegrationTest/Streetcode.XIntegrationTest.csproj
Streetcode/Streetcode.XUnitTest/MediatRTests/Account/Login/LoginUserHandlerTests.cs
Streetcode/Streetcode.XUnitTest/MediatRTests/Account/LoginWithGoogle/LoginWithGoogleHandlerTests.cs

253 google auth

---

Streetcode/Streetcode.WebApi/Program.cs

Add Swagger for Prod

---

Streetcode/Streetcode.WebApi/Extensions/ServiceCollectionExtensions.cs
Streetcode/Streetcode.WebApi/Properties/launchSettings.json

Env variable Host wsa removed.
Method addBlobStorage was removed

Blob fixed

---

Streetcode/Streetcode.BLL/MediatR/Account/Login/LoginUserHandler.cs

replace accestoken to refreshtoken
